Task/update restsharp and dotnet 6/1
Penneo/sdk-net pull request #152
Opened 2022-10-18 13:22 UTC by HeadCookie

2022-10-18 17:49 UTC, w3dev-dk submitted a review, later dismissed
LGTM but I don't have that much experience with C#.

I have one comment for the release notes which I thing you should consider but if the tests passes and it can build then you can get an approval from me 👍

2022-10-18 17:49 UTC, w3dev-dk commented on CHANGELOG.md
> +- Updated to .NET 6.0
Maybe add which versions those has been updated from as it will give some context to the severity of the update ;)

2022-10-18 21:06 UTC, HeadCookie commented on CHANGELOG.md
> +- Updated to .NET 6.0
Done :)

2022-10-19 05:41 UTC, w3dev-dk approved these changes

2022-10-19 07:40 UTC, fabianbadoi requested changes

2022-10-19 07:40 UTC, fabianbadoi commented on Src/Penneo/Connector/ApiConnector.cs
> +                UserAgent = "Penneo_sdk-net_" + Info.Version
Since we're using a `_` in both `Penneo_sdk` and as a version separator, it will be harder now to write scripts to work on access log data for the .net project.

Unless you have a very strong reason to change this, please use the same convention as the PHP sdk.

2022-10-19 12:25 UTC, fabianbadoi approved these changes

2022-10-19 12:29 UTC, merged