Use await instead of .result
Penneo/sdk-net pull request #164
Opened 2023-03-02 22:14 UTC by HeadCookie

2023-03-14 13:12 UTC, w3dev-dk reviewed
I would like  second reviewer on this one

2023-03-14 13:12 UTC, w3dev-dk commented on Src/Penneo/(Model)/SignatureLine.cs
>  }
Misses empty line at end of file

2023-03-14 13:12 UTC, w3dev-dk commented on Src/PenneoTests/CaseFileTests.cs
> +using System.Threading.Tasks;
Is this needed?

2023-03-14 13:12 UTC, w3dev-dk commented on Src/PenneoTests/QueryTests.cs
> +            FindCollectionTest(con, async () => await q.FindAll<CaseFile>());
Don't C3 have a auto formatter to solve issues like here where you sometimes has a space and sometimes not? `async ()` vs `async()`

2023-03-14 13:14 UTC, w3dev-dk commented on Src/Penneo/(Model)/CaseFile.cs
>          }
If anything else is marked as obsolete and has been it for a long time then maybe consider taking advantage of the new major version to cleanup

2023-03-14 13:19 UTC, HeadCookie commented on Src/PenneoTests/QueryTests.cs
> +            FindCollectionTest(con, async () => await q.FindAll<CaseFile>());
It's an async anonymous method thus the white space. :)

2023-03-14 13:34 UTC, w3dev-dk commented on Src/PenneoTests/QueryTests.cs
> +            FindCollectionTest(con, async () => await q.FindAll<CaseFile>());
My question was more that you are not consistent in the way you format the code. Some places you have the space, others you don't...

2023-03-14 13:47 UTC, HeadCookie commented on Src/PenneoTests/QueryTests.cs
> +            FindCollectionTest(con, async () => await q.FindAll<CaseFile>());
Ah fair - now I understand. I will fix that

2023-03-14 13:47 UTC, HeadCookie commented on Src/PenneoTests/CaseFileTests.cs
> +using System.Threading.Tasks;
Nope - good catch

2023-03-16 09:38 UTC, HeadCookie commented on Src/Penneo/(Model)/CaseFile.cs
>          }
Removed obselete methods

2023-03-16 14:17 UTC, w3dev-dk reviewed
I could approve it but I think we should discus it on the team. It's a big change and anyone using the SDK will have to refactor everything when upgrading...

My concern is that if we are going to ask our customers to re-factore everything then I would prefer to do that one time only - and should that one time be to refactor to use async or should it be fixing our OpenAPI spec so they can auto generate their own SDK?

2023-05-10 10:29 UTC, fabianbadoi commented on Src/Penneo/(Model)/Document.cs
> -        public string OptionsJson { get; set; }
Why are we dropping this?

2023-05-10 10:29 UTC, fabianbadoi commented on Src/Penneo/(Model)/Document.cs
> -        public Dictionary<string, object> Options
Why are we dropping this?

2023-05-10 10:31 UTC, fabianbadoi requested changes
Looks good, but I don't understand why we're removing document.options

2023-05-10 10:36 UTC, HeadCookie commented on Src/Penneo/(Model)/Document.cs
> -        public string OptionsJson { get; set; }
They are marked as deprecated in the API and obsolete here (one should use opts instead). If we are making a major version we might as well do some housekeeping - at least that was the thought.

2023-05-10 10:45 UTC, HeadCookie commented on Src/Penneo/(Model)/Document.cs
> -        public string OptionsJson { get; set; }
I'll add it to the changelog

2023-05-10 11:57 UTC, fabianbadoi approved these changes

2023-07-11 10:55 UTC, w3dev-dk approved these changes

2023-07-11 11:02 UTC, merged